### ISSUE TITLE
Missing maintainers

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/r-matrix-feedstock#1]
It seems there were 2 PRs merged at staged-recipes that contained `r-matrix`. As they had different maintainer listings, it seems one won out and the other maintainers were not included. Opening this issue to notify about this problem and make the maintainers aware. This should be fixable by simply adding the missing maintainers' GitHub handles to the `recipe-maintainers` listing.

cc @bgruening @johanneskoester

xref: https://github.com/conda-forge/staged-recipes/pull/2668
xref: https://github.com/conda-forge/staged-recipes/pull/2309

**Comment by bgruening** [comment]
@jakirkham thanks for noticing. @ocefpaf if you like you can add us as maintainer.
Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf if you like you can add us as maintainer.

Go for it.

**Comment by jakirkham** [comment]
Have manually removed you guys from the team for now since you aren't on the list in the recipe yet. Though happy to make sure you get added once you add your handles to the list.
